### PR TITLE
Migrate TravisCI and CircleCI to GitHub Actions

### PR DESCRIPTION
**Pull request by saheerb**

### CODE REVIEW

**Comment by saheerb** [comment]
Unfortunately GitHub Action wont run from PR of a fork (if there was no GitHub Action already in the repository). Evidence of successful GitHub Action can be seen in: https://github.com/saheerb/mbed-os-example-blinky-baremetal/actions/runs/1245266345

**Comment by saheerb** [comment]
@LDong-Arm  @Patater can you review this please?

**Review by LDong-Arm — APPROVED** [review]
LGTM

The CircleCI failure is due to webhook not removed. I don't have permissions to do it on this repo. @ARMmbed/mbed-os-maintainers Could you please go to "Settings" -> "Webhooks" to configure it?

**Comment by saheerb** [comment]
@jamesbeyond  already disabled it. I will close and reopen.

**Comment by LDong-Arm** [comment]
The error is from two hours ago. Reopening doesn't seem to remove previous runs of checks that no longer exist. As you confirmed it's now disabled, I'm merging this PR.

**Comment by saheerb** [comment]
Did a squash push to remove the error ;-)

**Pull request merged**
